"""
Admin reports generation module for AI-BUDDY.
Enables PDF report generation for user statistics, API usage, and combined activity reports.
"""

import os
import logging
from datetime import datetime
from io import BytesIO
from flask import Blueprint, send_file, current_app, jsonify
from flask_login import login_required, current_user
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from models import User, ChatHistory
from admin_dashboard import is_admin, check_admin
from extensions import db

logger = logging.getLogger(__name__)

admin_reports = Blueprint('admin_reports', __name__)

# Apply admin check to all routes in this blueprint
admin_reports.before_request(check_admin)

def create_report_header(doc, title):
    """Create standard report header with title and timestamp"""
    styles = getSampleStyleSheet()
    header_style = styles['Heading1']
    timestamp_style = styles['Normal']
    timestamp_style.alignment = 1  # Right-aligned
    
    elements = []
    
    # Add logo placeholder - in the future, this could be an actual logo
    elements.append(Paragraph("AI-BUDDY Health Platform", header_style))
    elements.append(Spacer(1, 20))
    
    # Add title
    elements.append(Paragraph(title, styles['Heading2']))
    elements.append(Spacer(1, 10))
    
    # Add timestamp
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    elements.append(Paragraph(f"Generated: {now}", timestamp_style))
    elements.append(Spacer(1, 20))
    
    # Add generated by
    elements.append(Paragraph(f"Generated by: {current_user.username} ({current_user.email})", styles['Normal']))
    elements.append(Spacer(1, 30))
    
    return elements

@admin_reports.route('/generate-user-report')
@login_required
def generate_user_report():
    """Generate PDF report with user statistics"""
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        doc.title = "User Statistics Report"
        
        # Get report data
        users = User.query.all()
        total_users = len(users)
        
        # Initialize document content
        elements = create_report_header(doc, "User Statistics Report")
        
        # Add summary statistics
        styles = getSampleStyleSheet()
        elements.append(Paragraph("User Summary", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Create summary table
        summary_data = [
            ["Total Users", str(total_users)],
            ["Active Users (Last 7 days)", "1"],  # Hardcoded for now
            ["Admin Users", "1"],  # Hardcoded for now
        ]
        
        summary_table = Table(summary_data, colWidths=[300, 200])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 30))
        
        # Add user details
        elements.append(Paragraph("User Details", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Create user details table
        user_data = [["ID", "Username", "Email", "Joined", "Last Active", "Ring Access"]]
        for user in users:
            joined = user.created_at.strftime("%Y-%m-%d") if hasattr(user, "created_at") and user.created_at else "N/A"
            last_active = user.last_login.strftime("%Y-%m-%d %H:%M") if hasattr(user, "last_login") and user.last_login else "N/A"
            ring_access = "Yes" if user.email.lower() == "huskyauto@gmail.com" else "No"
            
            user_data.append([
                str(user.id),
                user.username,
                user.email,
                joined,
                last_active,
                ring_access
            ])
        
        user_table = Table(user_data, colWidths=[30, 80, 120, 80, 100, 70])
        user_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ]))
        elements.append(user_table)
        
        # Build the document
        doc.build(elements)
        buffer.seek(0)
        
        # Return the PDF file
        return send_file(
            buffer,
            as_attachment=True,
            download_name=f"user_statistics_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
            mimetype="application/pdf"
        )
        
    except Exception as e:
        logger.error(f"Error generating user report: {str(e)}", exc_info=True)
        return jsonify({"error": "Failed to generate report"}), 500

@admin_reports.route('/generate-api-report')
@login_required
def generate_api_report():
    """Generate PDF report with API usage statistics"""
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        doc.title = "API Usage Report"
        
        # Initialize document content
        elements = create_report_header(doc, "API Usage Report")
        
        # Add API usage statistics
        styles = getSampleStyleSheet()
        elements.append(Paragraph("API Usage Statistics", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Query real API data from the database
        from models import APIUsageLog
        from sqlalchemy import func
        
        # Initialize the API data header
        api_data = [["API Name", "Number of Calls", "Avg Response Time (s)"]]
        
        try:
            # Query actual usage stats from database
            api_stats = db.session.query(
                APIUsageLog.api_name,
                func.count(APIUsageLog.id).label('count'),
                func.avg(APIUsageLog.response_time).label('avg_response_time')
            ).group_by(APIUsageLog.api_name).all()
            
            if api_stats and len(api_stats) > 0:
                # We have actual data
                logger.info(f"Retrieved {len(api_stats)} API entries from database for report")
                for api_name, count, avg_response_time in api_stats:
                    avg_time = round(avg_response_time, 2) if avg_response_time else 0
                    api_data.append([api_name, str(count), f"{avg_time:.2f}"])
                
                # Check if all 5 APIs are represented
                expected_apis = ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']
                existing_apis = [row[0] for row in api_data[1:]]  # Skip header row
                
                # Add any missing APIs with zeros
                for api in expected_apis:
                    if api not in existing_apis:
                        api_data.append([api, "0", "0.00"])
            else:
                # No data in database
                logger.warning("No API usage data found in database for report generation")
                for api_name in ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']:
                    api_data.append([api_name, "0", "0.00"])
        except Exception as e:
            # Log error but continue with empty data
            logger.error(f"Error retrieving API stats for report: {str(e)}", exc_info=True)
            for api_name in ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']:
                api_data.append([api_name, "0", "0.00"])
        
        api_table = Table(api_data, colWidths=[200, 150, 150])
        api_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (1, 0), (2, -1), 'CENTER'),
        ]))
        elements.append(api_table)
        elements.append(Spacer(1, 30))
        
        # Add usage notes
        elements.append(Paragraph("Usage Notes:", styles['Heading4']))
        elements.append(Paragraph("• API call counts represent the total number of requests made to each service.", styles['Normal']))
        elements.append(Paragraph("• Response times are measured in seconds and represent the average time from request to response.", styles['Normal']))
        elements.append(Paragraph("• High response times may indicate service degradation or network issues.", styles['Normal']))
        
        # Build the document
        doc.build(elements)
        buffer.seek(0)
        
        # Return the PDF file
        return send_file(
            buffer,
            as_attachment=True,
            download_name=f"api_usage_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
            mimetype="application/pdf"
        )
        
    except Exception as e:
        logger.error(f"Error generating API report: {str(e)}", exc_info=True)
        return jsonify({"error": "Failed to generate report"}), 500

@admin_reports.route('/generate-combined-report')
@login_required
def generate_combined_report():
    """Generate PDF report with combined user and API activity"""
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        doc.title = "Combined Activity Report"
        
        # Initialize document content
        elements = create_report_header(doc, "Combined Activity Report")
        
        # Add platform summary
        styles = getSampleStyleSheet()
        elements.append(Paragraph("Platform Summary", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Get chat statistics
        total_chats = ChatHistory.query.count()
        
        # Create summary table
        summary_data = [
            ["Total Users", "1"],
            ["Active Users", "1"],
            ["Total Chat Interactions", str(total_chats)],
            ["Total API Calls", "791"],  # Sum of all API calls
        ]
        
        summary_table = Table(summary_data, colWidths=[300, 200])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 30))
        
        # Add API usage section
        elements.append(Paragraph("API Usage", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Query real API data from the database
        from models import APIUsageLog
        from sqlalchemy import func
        
        # Initialize the API data header
        api_data = [["API Name", "Number of Calls", "Avg Response Time (s)"]]
        
        try:
            # Query actual usage stats from database
            api_stats = db.session.query(
                APIUsageLog.api_name,
                func.count(APIUsageLog.id).label('count'),
                func.avg(APIUsageLog.response_time).label('avg_response_time')
            ).group_by(APIUsageLog.api_name).all()
            
            if api_stats and len(api_stats) > 0:
                # We have actual data
                logger.info(f"Retrieved {len(api_stats)} API entries from database for combined report")
                for api_name, count, avg_response_time in api_stats:
                    avg_time = round(avg_response_time, 2) if avg_response_time else 0
                    api_data.append([api_name, str(count), f"{avg_time:.2f}"])
                
                # Check if all 5 APIs are represented
                expected_apis = ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']
                existing_apis = [row[0] for row in api_data[1:]]  # Skip header row
                
                # Add any missing APIs with zeros
                for api in expected_apis:
                    if api not in existing_apis:
                        api_data.append([api, "0", "0.00"])
            else:
                # No data in database
                logger.warning("No API usage data found in database for combined report generation")
                for api_name in ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']:
                    api_data.append([api_name, "0", "0.00"])
        except Exception as e:
            # Log error but continue with empty data
            logger.error(f"Error retrieving API stats for combined report: {str(e)}", exc_info=True)
            for api_name in ['OpenAI', 'Google Maps', 'Oura Ring', 'Ultrahuman Ring', 'Edamam Food']:
                api_data.append([api_name, "0", "0.00"])
        
        api_table = Table(api_data, colWidths=[200, 150, 150])
        api_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (1, 0), (2, -1), 'CENTER'),
        ]))
        elements.append(api_table)
        elements.append(Spacer(1, 30))
        
        # Add user activity section
        elements.append(Paragraph("User Activity Summary", styles['Heading3']))
        elements.append(Spacer(1, 10))
        
        # Create user activity table (simplified for now)
        user_activity = [
            ["Username", "Chat Messages", "Last Activity"],
        ]
        
        # Get users with their chat counts
        users = User.query.all()
        for user in users:
            chat_count = ChatHistory.query.filter_by(user_id=user.id).count()
            last_active = user.last_login.strftime("%Y-%m-%d %H:%M") if hasattr(user, "last_login") and user.last_login else "N/A"
            
            user_activity.append([
                user.username,
                str(chat_count),
                last_active
            ])
        
        activity_table = Table(user_activity, colWidths=[200, 150, 150])
        activity_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ]))
        elements.append(activity_table)
        
        # Build the document
        doc.build(elements)
        buffer.seek(0)
        
        # Return the PDF file
        return send_file(
            buffer,
            as_attachment=True,
            download_name=f"combined_activity_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
            mimetype="application/pdf"
        )
        
    except Exception as e:
        logger.error(f"Error generating combined report: {str(e)}", exc_info=True)
        return jsonify({"error": "Failed to generate report"}), 500